import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, LockKeyhole, ShieldCheck, Users } from "lucide-react";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import { gunneboRanges } from "../../gunnebo-products";
import { boonedamRanges } from "../../boonedam-ranges";

const brands = [
  { name: "Gunnebo", slug: "gunnebo", ranges: gunneboRanges },
  { name: "Boon Edam", slug: "boonedam", ranges: boonedamRanges },
];
const total = brands.reduce((sum,brand)=>sum+Object.values(brand.ranges).reduce((count,range)=>count+range.products.length,0),0);
export const metadata={title:"Access Control & Turnstile Products | Synoveta",description:"Explore all Gunnebo and Boon Edam tripod and full-height turnstile products."};

export default function AccessControlCatalog(){return <><Header activePage="products"/><main className="bosch-catalog"><section className="catalog-hero"><div className="container catalog-hero-inner"><div><p className="eyebrow">Secure entrance solutions</p><h1>Access Control &amp; Turnstile</h1><p>Explore all available entrance-control products together, or browse dedicated collections by brand.</p><div className="catalog-benefits"><span><ShieldCheck/> Trusted global brands</span><span><LockKeyhole/> Secure access</span><span><Users/> Efficient pedestrian flow</span></div></div><div className="conference-hero-product"><Image src="/product-assets/Access Control & Turnstile.webp" alt="Access control and turnstiles" fill priority sizes="(max-width:760px) 85vw,34vw"/></div></div></section><section className="catalog-body"><div className="container"><div className="catalog-heading"><div><p className="eyebrow">Complete product range</p><h2>All turnstile products</h2></div><p>{total} products across {brands.length} brands</p></div><div className="brand-page-links"><span>Browse by brand</span>{brands.map(brand=><Link key={brand.slug} href={`/products/access-control-turnstile/${brand.slug}/`}>{brand.name}<ArrowRight/></Link>)}</div><div className="all-brand-products">{brands.map(brand=><section className="bosch-group" key={brand.slug}><div className="group-title"><div><h3>{brand.name}</h3><span>{Object.values(brand.ranges).reduce((sum,range)=>sum+range.products.length,0)} products</span></div><Link href={`/products/access-control-turnstile/${brand.slug}/`}>View {brand.name} range <ArrowRight/></Link></div><div className="bosch-grid">{Object.entries(brand.ranges).flatMap(([subcategory,range])=>range.products.map(product=><article className="bosch-card" key={`${brand.slug}-${product.slug}`}><Link className="bosch-card-image" href={`/products/access-control-turnstile/${brand.slug}/${subcategory}/${product.slug}/`}><Image src={product.image} alt={product.name} fill sizes="(max-width:600px) 100vw,(max-width:1000px) 50vw,25vw"/></Link><div className="bosch-card-copy"><span>{brand.name} · {range.title}</span><h4><Link href={`/products/access-control-turnstile/${brand.slug}/${subcategory}/${product.slug}/`}>{product.name}</Link></h4><p>{product.summary}</p><Link className="card-link" href={`/products/access-control-turnstile/${brand.slug}/${subcategory}/${product.slug}/`}>View details <ArrowRight/></Link></div></article>))}</div></section>)}</div><div className="catalog-cta"><div><CheckCircle2/><span><b>Need help choosing?</b><small>Our entrance-control specialists can help select the right turnstile for your project.</small></span></div><a className="primary-btn" href="mailto:info@synoveta.com">Talk to an expert <ArrowRight/></a></div></div></section></main><Footer/></>}
