import Image from "next/image";
import Link from "next/link";
import { ArrowRight, AudioLines, BadgeCheck, Gem, Camera, Check, ChevronRight, Cpu, Globe2, Mic2, Monitor, Network, Radio, Settings2, ShieldCheck, Signal, Users, Wifi } from "lucide-react";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import "./conference-landing.css";
import "./conference-opening.css";
import "./conference-hero.css";
import ConferenceHero from "./ConferenceHero";
import { ConferenceProductRail } from "./ConferenceControls";

const base = "/Confeernce system";
const wired = `${base}/digital-wired- conference-system`;
const wireless = `${base}/wifi-wireless-conference-system`;
const series = [
  { title: "Digital Wired Conference", description: "Reliable, professional wired discussion systems for boardrooms, council chambers and formal meeting spaces.", image: `${wired}/digital-wired- conference-system.webp`, scene: `${base}/landing/wired-v3.webp`, href: "/products/conference-system/digital-wired-conference/", button: "View Wired Systems", points: ["Stable and reliable installation", "Ideal for permanent meeting rooms", "Supports advanced discussion control", "Camera tracking compatible"] },
  { title: "WiFi Wireless Conference", description: "Flexible wireless discussion systems for modern meeting rooms, fast deployment and a clean table setup.", image: `${wireless}/wifi-wireless-conference-system.webp`, scene: `${base}/landing/wireless-v3.webp`, href: "/products/conference-system/wifi-wireless-conference/", button: "View Wireless Systems", points: ["Fast and flexible deployment", "Cleaner table setup with less cabling", "Ideal for modern and multi-purpose rooms", "Easy reconfiguration and expansion"] },
];
const capabilities = [
  [Mic2, "Crystal Clear Discussion Audio", "High speech intelligibility for productive meetings."],
  [Settings2, "Centralized Meeting Control", "Efficient management of discussion flow."],
  [Camera, "Camera Auto-Tracking", "Integration with compatible PTZ cameras."],
  [Network, "AV Integration", "Works with audio, displays and control systems."],
  [Wifi, "Wired & Wireless Flexibility", "Choose the right solution for your environment."],
  [Signal, "Scalable Deployment", "From meeting rooms to larger conference halls."],
];
const products = [
  ["SV-DWC-C200S", "Digital conference controller for professional wired systems.", `${wired}/Digital-Conference-System-Controller-SV-DWC-C200S.webp`, "digital-wired-conference/sv-dwc-c200s"],
  ["SV-DWC-C800S", "Wireless conference controller for flexible discussion environments.", `${wireless}/Conference-System-Controller-SV-DWC-C800S.webp`, "wifi-wireless-conference/sv-dwc-c800s"],
  ["SV-DWC-M230C", "Chairman unit with priority control and elegant design.", `${wired}/Chairman-Unit-SV-DWC-M230C.webp`, "digital-wired-conference/sv-dwc-m230c"],
  ["SV-DWC-M230D", "Delegate unit with clear speech pickup and intuitive operation.", `${wired}/Chairman-Unit-SV-DWC-M230D.webp`, "digital-wired-conference/sv-dwc-m230d"],
  ["SV-WWC-M809D", "Wireless delegate unit for flexible conference spaces.", `${wireless}/Wireless-Chairman-Unit-SV-WWC-M809D.webp`, "wifi-wireless-conference/sv-wwc-m809d"],
];
products.push(["SV-WWC-M810C", "Wireless chairman unit with a large touch display.", `${wireless}/Wireless-Chairman-Unit-SV-WWC-M810C.webp`, "wifi-wireless-conference/sv-wwc-m810c"], ["SV-DWC-M805D", "Digital delegate unit for professional discussion systems.", `${wired}/SV-DWC-M805D.webp`, "digital-wired-conference/sv-dwc-m805d"]);
const applications = [
  ["Corporate Boardrooms", `${base}/conference-system-setup-for-meeting-room.webp`],
  ["Government Meeting Rooms", `${base}/landing/government.webp`],
  ["Council Chambers", `${base}/landing/council.webp`],
  ["Educational Institutions", `${base}/landing/education.webp`],
  ["Training Centres", `${base}/landing/training.webp`],
  ["Conference Halls", `${base}/landing/hall.webp`],
  ["Control & Command Rooms", "/LED-Display/industry-control-room.webp"],
  ["International Projects", `${base}/landing/international.webp`],
];
const faqs = [
  ["What types of conference systems does Synoveta offer?", "Synoveta offers digital wired and WiFi wireless discussion systems for professional meeting environments."],
  ["What is the difference between wired and wireless conference systems?", "Wired systems suit permanent installations; wireless systems offer flexible layouts and faster deployment with less cabling."],
  ["How do I choose between a wired and wireless system?", "Consider room layout, participant count, installation conditions and how often seating will change."],
  ["Can systems be configured for different project sizes?", "Yes. Configurations can be tailored to room capacity, required functions, integration needs and project scope."],
  ["Can Synoveta conference systems support camera tracking?", "Selected configurations can integrate with compatible PTZ cameras for speaker tracking."],
  ["Can conference systems integrate with professional AV systems?", "Compatible systems can connect with displays, audio equipment, PTZ cameras and central control solutions."],
  ["Are these systems suitable for international projects?", "Yes. Solutions can be configured for project and regional requirements with support from our partner network."],
  ["How can I select the right solution for my project?", "Share the room size, participant count, preferred architecture and required AV functions to discuss a configuration."],
];

export const metadata = { title: "Professional Conference Systems | Synoveta", description: "Explore Synoveta digital wired and WiFi wireless conference systems for clear, reliable meeting communication." };
function Heading({ eyebrow, title, description }) { return <div className="cs-heading"><span className="cs-eyebrow">{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>; }

export default function ConferenceCatalogPage() { return <><Header activePage="products"/><main className="cs-page">
  <ConferenceHero/>
  <div className="cs-proof"><div className="cs-container">{[[Gem,"European-Level","Product Design"],[Radio,"Wired & Wireless","Solutions"],[Camera,"Camera Tracking","Support"],[Monitor,"AV Integration","Ready"]].map(([Icon,a,b])=><div key={a}><Icon/><span>{a}<br/>{b}</span></div>)}</div></div>
  <section className="cs-series cs-section" id="conference-series"><div className="cs-container"><Heading eyebrow="Find your ideal solution" title="Choose Your Conference System" description="Select a digital wired or WiFi wireless conference system to match your meeting space and installation requirements."/><div className="cs-series-grid">{series.map(item=><article className="cs-series-card" key={item.title}><Image className="cs-series-scene" src={item.scene} alt="" fill sizes="(max-width: 760px) 100vw, 50vw"/><div className="cs-series-gradient"/><div className="cs-series-copy"><h3>{item.title}</h3><p>{item.description}</p><ul>{item.points.map(point=><li key={point}><Check/>{point}</li>)}</ul><Link href={item.href} className="cs-pill">{item.button}<ArrowRight/></Link></div></article>)}</div></div></section>
  <section className="cs-capabilities cs-section"><div className="cs-container"><Heading eyebrow="Key features" title="Advanced Capabilities for Modern Conference Environments" description="Synoveta conference systems are designed to support clear communication, efficient control and professional integration."/><div className="cs-capability-grid">{capabilities.map(([Icon,title,description])=><article key={title}><Icon/><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
  <section className="cs-meeting" id="meeting-rooms"><div className="cs-meeting-photo"><Image src={`${base}/conference-system-setup-for-meeting-room.webp`} alt="Conference system installed in a professional meeting room" fill sizes="(max-width: 760px) 100vw, 50vw"/></div><div className="cs-meeting-copy"><span className="cs-eyebrow">Smart meeting environments</span><h2>Professional Conference Setup<br/>for Modern Meeting Rooms</h2><p>Synoveta conference systems deliver clear communication, reliable control and seamless integration for boardrooms, meeting spaces and professional discussion environments.</p><div className="cs-meeting-benefits">{[[Mic2,"Clear Communication","High speech intelligibility"],[Settings2,"Centralized Control","Efficient meeting management"],[Monitor,"Seamless Integration","Compatible AV systems"]].map(([Icon,title,description])=><div key={title}><Icon/><span><strong>{title}</strong><small>{description}</small></span></div>)}</div></div></section>
  <section className="cs-smart cs-section"><div className="cs-container cs-smart-grid"><div className="cs-smart-copy"><span className="cs-eyebrow">Intelligent meeting solutions</span><h2>Smarter Meetings with Camera Tracking and AV Integration</h2><p>Selected system configurations support compatible PTZ cameras for active speaker tracking, along with connectivity to professional audio, display and control environments.</p><ul>{["Active speaker camera tracking", "PTZ camera compatibility", "Audio and display system integration", "Professional meeting room workflow support"].map(point=><li key={point}><Check/>{point}</li>)}</ul><Link className="cs-pill" href="/contact/">Learn More <ArrowRight/></Link></div><div className="cs-smart-visual"><Image src={`${base}/landing/integration.webp`} alt="Illustrative camera tracking and AV integration with conference devices" fill sizes="(max-width: 760px) 100vw, 55vw"/><div className="cs-smart-visual-labels"><span><Camera/>Camera Tracking</span><span><Network/>AV Integration</span><span><Radio/>Live Streaming</span></div></div></div></section>
  <section className="cs-products cs-section"><div className="cs-container"><div className="cs-section-row"><Heading eyebrow="Featured products" title="Explore Synovetaâ€™s Conference System Range" description="A selection of our most popular conference system products."/><Link href={series[0].href}>View All Products <ArrowRight/></Link></div><ConferenceProductRail>{products.map(([model,description,image,slug])=><Link className="cs-product-card" key={model} href={`/products/conference-system/${slug}/`}><div className="cs-product-image"><Image src={image} alt={`${model} conference device`} fill sizes="(max-width: 600px) 50vw, 20vw"/></div><strong>{model}</strong><p>{description}</p><span>View Details <ArrowRight/></span></Link>)}</ConferenceProductRail></div></section>
  <section className="cs-applications cs-section"><div className="cs-container"><Heading eyebrow="Wide range of applications" title="Designed for Professional Communication Environments" description="Synoveta conference systems are suitable for a wide range of meeting spaces and industries."/><div className="cs-application-grid">{applications.map(([title,image])=><article key={title}><div><Image src={image} alt={title} fill sizes="(max-width: 600px) 50vw, 13vw"/></div><h3>{title}</h3></article>)}</div></div></section>
  <section className="cs-global"><div className="cs-container cs-global-grid"><div className="cs-global-copy"><span className="cs-eyebrow">Global reach</span><h2>A Trusted Partner for International Conference Projects</h2><p>Synoveta supports conference projects through an international presence, dependable supply and local project expertise.</p><Link className="cs-pill" href="/partners/">Our Global Presence <ArrowRight/></Link></div><div className="cs-global-map" role="img" aria-label="World map highlighting Milan, Dubai and Singapore"><div className="cs-map-glow"/><Image src={`${base}/landing/world-map.svg`} alt="" fill sizes="(max-width: 760px) 100vw, 42vw"/><svg className="cs-map-routes" viewBox="0 0 720 390" aria-hidden="true"><path className="cs-route-base" d="M366 126 Q443 116 480 177"/><path className="cs-route-flow" d="M366 126 Q443 116 480 177"/><path className="cs-route-base" d="M480 177 Q546 160 573 229"/><path className="cs-route-flow" d="M480 177 Q546 160 573 229"/><g className="cs-map-point"><circle className="cs-map-pulse" cx="366" cy="126" r="18"/><circle className="cs-map-ring" cx="366" cy="126" r="8"/><circle className="cs-map-core" cx="366" cy="126" r="4"/></g><g className="cs-map-point cs-map-point-dubai"><circle className="cs-map-pulse" cx="480" cy="177" r="18"/><circle className="cs-map-ring" cx="480" cy="177" r="8"/><circle className="cs-map-core" cx="480" cy="177" r="4"/></g><g className="cs-map-point cs-map-point-singapore"><circle className="cs-map-pulse" cx="573" cy="229" r="18"/><circle className="cs-map-ring" cx="573" cy="229" r="8"/><circle className="cs-map-core" cx="573" cy="229" r="4"/></g></svg></div><div className="cs-global-locations"><div className="cs-global-locations-heading">OUR LOCATIONS <span>01 / 03</span></div><div className="cs-global-location"><span className="cs-flag cs-flag-italy"/><span><strong>Italy Head Office</strong><small>Milan, Italy</small></span></div><div className="cs-global-location"><span className="cs-flag cs-flag-uae"/><span><strong>Dubai Office</strong><small>Dubai, United Arab Emirates</small></span></div><div className="cs-global-location"><span className="cs-flag cs-flag-singapore"/><span><strong>Singapore Office</strong><small>Singapore</small></span></div><div className="cs-global-locations-foot"><Globe2/> Connected across regions</div></div></div></section>
  <section className="cs-faq cs-section"><div className="cs-container"><div className="cs-section-row"><Heading eyebrow="FAQ" title="Frequently Asked Questions" description="Find quick answers about selecting, configuring and integrating Synoveta conference systems."/><Link href="/contact/">Ask a Question <ArrowRight/></Link></div><div className="cs-faq-grid">{[faqs.slice(0,4),faqs.slice(4)].map((column,i)=><div key={i}>{column.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div>)}</div></div></section>
  <section className="cs-cta"><div className="cs-container"><div><h2>Need Help Choosing the Right Conference System?</h2><p>Discuss your project with our team to find the best wired or wireless solution for your meeting environment.</p></div><div><Link href="/contact/" className="cs-button cs-button-light">Request a Quote <ArrowRight/></Link><Link href="/contact/" className="cs-button cs-button-transparent">Contact Our Team <ChevronRight/></Link></div></div></section>
  </main><Footer/></>; }
