import Image from "next/image";
import Link from "next/link";
import {ArrowRight,Building2,CheckCircle2,Compass,Eye,Globe2,Handshake,Headphones,Leaf,Lightbulb,Megaphone,PackageCheck,Settings,ShieldCheck,Sparkles,Target,Truck,Users} from "lucide-react";
import Header from "../components/Header";
import Footer from "../components/Footer";

const stats=[["2012","Established","Built on experience, driven by innovation.",Building2],["50+","Countries Served","Delivering technology solutions across international markets.",Globe2],["200+","Global Partners","A growing network of distributors, dealers and system integrators.",Users],["10000+","Projects Completed","Solutions successfully delivered across multiple industries and applications.",CheckCircle2]];
const features=[["International Standards","We follow strict quality, compliance and operational standards.",ShieldCheck],["Reliable Partnership","We build long-term relationships based on trust, transparency and mutual growth.",Handshake],["Customer Focused","We listen, understand and deliver solutions aligned with real project requirements.",Users],["Innovation Driven","We continuously integrate practical technologies that create greater value for our customers.",Lightbulb]];
const values=[["Quality You Can Trust","We maintain strict standards across sourcing, assembly, testing and final delivery.",ShieldCheck],["Integrity in Everything We Do","We believe in transparent communication, ethical business practices and responsible decision-making.",Compass],["Innovation with Purpose","We adopt practical technologies that improve performance, reliability and customer value.",Lightbulb],["Growing Together","We build lasting relationships with customers, distributors and technology partners through mutual success.",Handshake]];
const strengths=[["Global Sourcing","We work with trusted manufacturers and component suppliers across international markets.",Globe2],["Assembly & Integration","Products and systems are professionally assembled, configured and integrated through our operational facilities.",Settings],["Quality Control","Rigorous testing and quality assurance are applied throughout every important stage of the process.",ShieldCheck],["Global Supply","Efficient logistics and international delivery capabilities support projects and partners worldwide.",Truck],["After-Sales Support","Our team provides responsive technical assistance and long-term support after delivery.",Headphones]];
const benefits=[["Competitive Product Portfolio","Access a broad portfolio of professional technology solutions designed for diverse commercial applications.",PackageCheck],["Technical Support","Receive practical technical guidance, product assistance and project-level support from our team.",Headphones],["Marketing Support","Benefit from product resources, marketing materials and brand support to help strengthen your local market presence.",Megaphone],["Long-Term Growth","Build a partnership focused on trust, market development, repeat business and mutual success.",Sparkles]];
const commitments=[["Quality You Can Trust","Consistent standards from sourcing to final delivery.",ShieldCheck],["Integrity in Everything We Do","Transparent and responsible business practices.",Handshake],["Sustainability & Responsibility","Smarter operations with consideration for long-term environmental and social impact.",Leaf],["Safety in All Operations","Safe, disciplined and responsible working practices across our operations.",CheckCircle2]];
function Heading({label,title,intro,left=false}){return <div className={"about-heading "+(left?"":"center")}><p className="about-eyebrow">{label}</p><h2>{title}</h2>{intro&&<p className="about-lead">{intro}</p>}</div>}
function Cards({items,className=""}){return <div className={"about-cards "+className}>{items.map(([title,copy,Icon])=><article key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div>}
export const metadata={title:"About Synoveta | Global Technology Partner"};
export default function AboutPage(){return <><Header activePage="about"/><main className="about-page">
<section className="about-hero"><Image src="/About page/banner image.webp" alt="Synoveta global headquarters" fill priority sizes="100vw"/><div className="about-hero-shade"/><div className="container about-hero-copy"><p>About Synoveta</p><h1>Global Vision.<br/><em>Quality You Can Trust.</em></h1><span>SYNOVETA is an international technology company headquartered in Italy with assembly operations in Italy and China. We deliver reliable technology solutions to customers and partners worldwide.</span></div></section>
<section className="about-section"><div className="container intro-grid"><div><Heading left label="Who we are" title={<>Your Global Technology<br/>Assembly &amp; Solutions Partner</>}/><p className="body-copy">Synoveta is an international technology company specializing in technology assembly, system integration and global supply of professional electronic and technology solutions. With operations in Italy and China, we combine European management standards with efficient production, sourcing and assembly capabilities to deliver reliable solutions to customers and partners worldwide.</p><Cards items={features} className="feature-cards"/></div><div className="stats-grid">{stats.map(([n,title,copy,Icon])=><article key={title}><Icon/><strong>{n}</strong><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="about-section tint"><div className="container"><Heading label="Our direction" title="Driven by Purpose. Focused on the Future."/><div className="mission-grid"><article><Target/><h3>Our Mission</h3><p>To provide reliable, high-quality and practical technology solutions through strong global sourcing, professional assembly, system integration and responsive support. We aim to help our partners and customers deliver successful projects with confidence, efficiency and long-term value.</p></article><article><Eye/><h3>Our Vision</h3><p>To become a globally trusted technology solutions brand recognized for quality, reliability, innovation and strong international partnerships, while continuously expanding our presence across new markets and industries.</p></article></div></div></section>
<section className="about-section"><div className="container"><Heading label="What guides us" title="Our Core Values" intro="Our values shape the way we work, build relationships and deliver technology solutions around the world."/><Cards items={values}/></div></section>
<section className="about-section strengths"><div className="container"><Heading label="What we do" title="Our Core Strengths" intro="We bring together global sourcing, precision assembly, strict quality control and international supply capabilities to deliver dependable technology solutions."/><Cards items={strengths} className="strength-cards"/><div className="actions"><Link className="about-btn primary" href="/#solutions">Learn more about our capabilities <ArrowRight/></Link></div></div></section>
<section className="about-section"><div className="container"><Heading label="Partner with Synoveta" title="Built for Long-Term Partnership" intro="We work closely with distributors, dealers, integrators and technology companies to create sustainable business opportunities in growing markets."/><Cards items={benefits}/><div className="actions"><Link className="about-btn primary" href="/partners">Find a partner <ArrowRight/></Link><Link className="about-btn secondary" href="/contact">Contact Synoveta</Link></div></div></section>
<section className="commitment"><div className="container"><div className="commitment-copy"><h2>Our Commitment</h2><p>We are committed to delivering dependable technology solutions through continuous improvement, ethical business practices, responsible operations and strong long-term partnerships.</p></div><Cards items={commitments} className="commitment-grid"/></div></section>
</main><Footer/></>}

