const wiredBase = '/Confeernce system/digital-wired- conference-system';
const wirelessBase = '/Confeernce system/wifi-wireless-conference-system';

import approvedConferenceProducts from './approved-conference-products.json';

const m809CommonFeatures = [
  'High-definition 2.4-inch full-color display showing microphone status, current time and date, speaking time, speaking timer, signal strength, battery power, ID number and other information.',
  '48 kHz sampling rate; the microphone powers on and connects in about 5 seconds.',
  'Intelligent fault detection for access-point failure, host communication failure and low signal strength.',
  'Speaking-timer and timed-speaking functions.',
  'Voice-control sensitivity and shutdown time can be adjusted through PC software.',
  '5-band EQ adjustment for optimizing the sound effect of all microphones.',
  'Supports sign-in; sign-in can be set and initiated through PC software.',
  'Uses 128-bit AES encryption and WPA/WPA2 wireless security to prevent eavesdropping and unauthorized access.',
  'Built-in rechargeable lithium battery provides approximately 10 hours of working time in speech mode.',
  'Includes one 3.5 mm stereo headphone jack.',
  'Supports Type-C program upgrades and 18 W fast charging; the microphone can be charged through a power bank.',
];

const m809Specifications = [
  ['Microphone type', 'Cardioid directional electret'],
  ['Frequency response', '80 Hzâ€“16 kHz'],
  ['Microphone input impedance', '1 kÎ©'],
  ['Sensitivity', 'âˆ’40 Â± 1.5 dB (0 dB = 1 V/Pa at 1 kHz)'],
  ['Maximum SPL', '100 dB (THD >3%)'],
  ['Signal-to-noise ratio', '>80 dB(A)'],
  ['Crosstalk', '>70 dB'],
  ['Dynamic range', '>80 dB'],
  ['THD', '<0.1%'],
  ['Maximum power consumption', '1.5 W'],
  ['Power supply', 'Lithium battery'],
  ['Charging method', 'Charge through the Type-C interface connected to the charging box'],
  ['Color', 'Black'],
  ['Sign-in function', 'Button sign-in'],
  ['Display', '2.4 inches'],
  ['Installation method', 'Desktop'],
  ['Wireless frequency range', '5.15â€“5.85 GHz'],
  ['Working time in speech mode', '10 hours'],
  ['Microphone rod length', '400 mm long black microphone rod'],
];

const m810CommonFeatures = [
  'High-definition 5.0-inch IPS full-color display showing microphone status, date and time, speaking time, signal strength and battery power.',
  '48 kHz sampling rate; the microphone powers on and connects in about 5 seconds.',
  'Intelligent fault detection alerts for access-point failure, host communication failure and low signal strength.',
  'Supports speaking-timer and timed-speaking functions.',
  'Voice-control sensitivity and shutdown time can be adjusted through PC software.',
  '5-band EQ adjustment helps optimize the sound effect of all microphones.',
  'Supports sign-in; sign-in can be set and initiated through PC software.',
  'Uses 128-bit AES encryption with WPA/WPA2 wireless security for improved conference confidentiality.',
  'Built-in 5,200 mAh lithium battery supports approximately 7 hours of speaking; an optional extended power supply supports up to 14 hours.',
  'Includes one 3.5 mm stereo headphone jack and a USB expansion interface.',
  'Supports Type-C program upgrades, 18 W fast charging, clock display, sign-in, voting and election functions.',
];

const m810Specifications = [
  ['Microphone type', 'Cardioid directional electret'],
  ['Frequency response', '80 Hzâ€“16 kHz'],
  ['Microphone input impedance', '1 kÎ©'],
  ['Sensitivity', 'âˆ’40 Â± 1.5 dB (0 dB = 1 V/Pa at 1 kHz)'],
  ['Maximum SPL', '100 dB (THD >3%)'],
  ['Signal-to-noise ratio', '>80 dB(A)'],
  ['Crosstalk', '>70 dB'],
  ['Dynamic range', '>80 dB'],
  ['THD', '<0.1%'],
  ['Maximum power consumption', '1.5 W'],
  ['Power supply', '5,200 mAh lithium battery'],
  ['Charging method', 'Type-C interface; supports 18 W fast charging'],
  ['Color', 'Black'],
  ['Sign-in function', 'Touch-screen sign-in'],
  ['Display', '5.0-inch IPS full-color display'],
  ['Installation method', 'Desktop'],
  ['Wireless frequency range', '5.15â€“5.85 GHz'],
  ['Working time in speech mode', 'Approximately 7 hours; up to 14 hours with optional extended power supply'],
  ['Microphone rod length', '400 mm long black microphone rod'],
];

const m805Features = [
  'Standard CAT6e connection with RJ45 connector; 48 kHz sampling rate and 80 Hz–16 kHz bandwidth.',
  'Original 5.0-inch IPS touch-screen interface with a low-key black design.',
  'Supports PC software microphone control and voice-control functions.',
  'Chairman priority function can close the speech of delegate units.',
  'TCP/IP protocol support including ICMP, HTTP, UDP, TCP and IGMP; supports PING packet function.',
  'Optional built-in 5 W fidelity speaker with howling suppression; the speaker automatically mutes when the microphone is on.',
  'Supports speech timing, timed speech and countdown speech functions.',
  'Adjustable voice-control sensitivity and 5-band EQ adjustment.',
  'Supports 63+1-channel simultaneous interpretation plus sign-in, voting and election functions.',
];
const m805Specifications = [
  ['Microphone type', 'Electret condenser microphone'],
  ['Microphone core directivity', 'Cardioid'],
  ['Frequency response', '80 Hz–16 kHz'],
  ['Microphone input impedance', '1 kΩ'],
  ['Sensitivity', '−46 ± 2 dB (0 dB = 1 V/Pa at 1 kHz)'],
  ['Maximum SPL', '120 dB (THD >3%)'],
  ['Signal-to-noise ratio', '>80 dB(A)'],
  ['Crosstalk', '>70 dB'],
  ['Dynamic range', '>80 dB'],
  ['THD', '<0.3%'],
  ['Maximum power consumption', '3 W'],
  ['Network port', '2, multi-level network port'],
  ['Power supply', 'Conference host'],
  ['Color', 'Silver gray'],
  ['Dimensions (L × W × H)', '166 × 109 × 128 mm'],
  ['Microphone rod length and color', 'Square microphone rod 215 mm black; long microphone rod 415 mm'],
  ['Installation method', 'Desktop'],
  ['Weight', '0.75 kg'],
];
const makeM805 = (suffix, role) => ({
  slug: 'sv-dwc-m805' + suffix.toLowerCase(),
  role: role + ' Unit',
  name: 'Full Digital Wired ' + role + ' Unit',
  model: 'SV-DWC-M805' + suffix,
  image: wiredBase + '/SV-DWC-M805' + suffix + '.webp',
  description: 'Full digital wired ' + role.toLowerCase() + ' unit with a 5-inch IPS touch screen and advanced conference functions.',
  features: m805Features,
  specifications: m805Specifications,
});
const make6200 = (suffix, role) => ({
  slug: 'svh-dwc-6200' + suffix.toLowerCase(),
  role: role + ' Unit',
  name: 'Digital Desktop ' + role + ' Microphone',
  model: 'SVH-DWC-6200' + suffix,
  image: wiredBase + '/SVH-DWC-6200' + suffix + '.webp',
  description: 'Professional digital desktop ' + role.toLowerCase() + ' microphone for intelligent conference systems and fixed meeting-room installations.',
  features: [
    'Gooseneck microphone design with adjustable height and angle.',
    'Suitable as a digital desktop ' + role.toLowerCase() + ' microphone for conference systems.',
    'Full zinc-alloy body with precision-machined base and anodized finish.',
    'Expandable dual backup for audio redundancy.',
    'Built-in AGC for stable audio pickup.',
    'Effective pickup distance: 50–60 cm.',
    'Ring Daisy-Chain connection via 8-PIN or CAT5.',
    'Compatible with intelligent digital conference system deployment.',
    'Auto camera tracking and screen switching support.',
    'Desktop installation for fixed meeting-room use.',
    'Clean professional appearance suitable for boardroom environments.',
    'Stable conference audio pickup for formal discussions.',
  ],
  specifications: [
    ['Product type', 'Digital desktop ' + role.toLowerCase() + ' microphone'],
    ['Original model', 'HY-6200' + suffix],
    ['Synoveta model', 'SVH-DWC-6200' + suffix],
    ['Series', 'Intelligent Digital Conference'],
    ['Installation type', 'Desktop'],
    ['Microphone design', 'Gooseneck'],
    ['Adjustment', 'Adjustable height / angle'],
    ['Body material / finish', 'Full zinc-alloy body, anodized finish'],
    ['Base', 'Precision-machined base'],
    ['Audio redundancy', 'Expandable dual backup'],
    ['AGC', 'Built-in'],
    ['Effective pickup distance', '50–60 cm'],
    ['Connection type', 'Ring Daisy-Chain (8-PIN or CAT5)'],
    ['Camera function', 'Auto camera tracking & screen switching'],
  ],
});
export const conferenceSystems = {
  'digital-wired-conference': {
    slug: 'digital-wired-conference',
    eyebrow: 'Digital conference solution',
    name: 'Digital Wired Conference System',
    shortName: 'Digital Wired Conference',
    modelFamily: 'SV-DWC Series',
    description: 'A purpose-built wired conference system for organised discussion in boardrooms, council chambers and formal meeting spaces.',
    heroImage: `${wiredBase}/digital-wired- conference-system-banner-image.webp`,
    overview: 'The SV-DWC series brings the controller, chairman unit and delegate unit together as one coordinated conference system. It is designed for permanent meeting-room installations where a clean, structured setup matters.',
    highlights: ['Dedicated central system controller', 'Separate chairman and delegate units', 'Designed as a coordinated wired system'],
    products: [
      {
        slug: 'sv-dwc-c200s',
        role: 'System Controller',
        name: 'Digital Conference System Controller',
        model: 'SV-DWC-C200S',
        image: `${wiredBase}/Digital-Conference-System-Controller-SV-DWC-C200S.webp`,
        description: 'High-performance central controller for the SV-DWC digital wired conference system.',
        features: [
          'Powered by a high-performance switching power supply; long-distance transmission will not affect sound quality.',
          'Anti-interference circuit design eliminates interference from mobile phone signals.',
          'Adopts a 4.3-inch full-view IPS capacitive touch screen for intuitive display and convenient adjustment of system parameters.',
          'Supports USB recording with high-fidelity WAV format output.',
          'Provides two-way, 8-core microphone unit interfaces. Each channel supports 45 units, allowing 90 units in total.',
          'A single host can connect up to 256 conference units through an extended power supply.',
          'Uses a hand-in-hand connection method, supports hot plugging, and is easy to install and maintain.',
          'Host functions include conference mode, system settings, video mode, unit ID editing mode, voting and USB recording.',
          'The RS-232 interface connects to a computer for check-in, voting, venue control, video adjustment, call-for-tea and other host operations.',
          'One balanced audio output can connect to sound reinforcement or recording equipment.',
        ],
        specifications: [
          ['Host power supply', 'AC 110â€“220 V / 50 Hz'],
          ['Microphone unit interface', '2 Ã— round DIN-8 sockets; 4 Ã— RJ45 network interfaces'],
          ['Audio total output auxiliary', '1 Ã— OUT VOL knob'],
          ['Audio total output', '1 Ã— BAL OUT (3-pin XLR port)'],
          ['Audio input auxiliary', '1 Ã— AUX VOL knob'],
          ['Audio recording output', '1 Ã— AUX OUT (Lotus socket)'],
          ['Audio input', '1 Ã— AUX IN (Lotus socket)'],
          ['Central control connector', '1 Ã— RS-232 serial port'],
          ['Video matrix connector', '1 Ã— VIDEO (9-pin)'],
          ['Phoenix connector', '1 Ã— VIDEO RS-422 (5-pin); 1 Ã— PELCO-D/485 Tâˆ’/B T+'],
          ['Small eight-core serial port', '1 Ã— VIDEO RS-232 (small eight-core)'],
          ['Frequency response', '20 Hzâ€“20 kHz'],
          ['Signal-to-noise ratio', '>96 dBA'],
          ['Total harmonic distortion', '<0.05%'],
          ['External dimensions (L Ã— W Ã— H)', '483 Ã— 323 Ã— 90 mm'],
          ['Color', 'Black'],
          ['Installation method', '19-inch standard cabinet'],
        ],
      },
      {
        slug: 'sv-dwc-m230c',
        role: 'Chairman Unit',
        name: 'Full Digital Wired Chairman Unit',
        model: 'SV-DWC-M230C',
        image: `${wiredBase}/Chairman-Unit-SV-DWC-M230C.webp`,
        description: 'Full digital wired chairman discussion unit for the SV-DWC conference system.',
        features: [
          'Patented appearance design with a high-end, solemn aesthetic aligned with modern design standards.',
          'Professional high-fidelity condenser microphone core with sensitive sound pickup and clear voice; frequency bandwidth reaches 20 Hzâ€“20 kHz.',
          'Anti-interference circuit design helps prevent interference from mobile phones and other electronic products.',
          'The microphone head has a speaking light ring that displays the speaking and closing status of the unit.',
          'The speaking switch button has a translucent speaking pattern that remains illuminated while speaking.',
          'Passive unit powered by the system host; the 24 V input voltage is within the safe range.',
          'Connected by a 1.5 m Ã— 2 m T-type 8-core wire and Category 6 network cable; shielding reduces strong electromagnetic interference.',
          'The microphone unit has a built-in speaker and independent electronic volume adjustment.',
          'Built-in 1.77-inch screen displays the clock, ID code, speaker volume, microphone switch icon and other information.',
        ],
        specifications: [
          ['Working voltage', 'DC 24 V (supplied by the host)'],
          ['Input and output', '8P-DIN T-cable; Category 6 network cable'],
          ['Input', 'Cardioid electret'],
          ['Sensitivity', 'âˆ’46 dBV/Pa'],
          ['Frequency response', '20 Hzâ€“20 kHz'],
          ['Input impedance', '2 kÎ©'],
          ['Directivity', '0Â°/180Â° > 20 dB (1 kHz)'],
          ['Equivalent noise', '20 dBA (SPL)'],
          ['Maximum microphone sound pressure level', '125 dB (THD <3%)'],
          ['Signal-to-noise ratio', '>80 dB'],
          ['Channel crosstalk', '>80 dB'],
          ['Total harmonic distortion', '<0.05%'],
          ['Display', '128 Ã— 32 PMOLED'],
          ['External dimensions (excluding microphone stem)', '188 Ã— 128 Ã— 52 mm'],
          ['Weight', '1.0 kg'],
          ['Color', 'Gray and black'],
          ['Installation', 'Desktop'],
        ],
      },
      {
        slug: 'sv-dwc-m230d',
        role: 'Delegate Unit',
        name: 'Full Digital Wired Delegate Unit',
        model: 'SV-DWC-M230D',
        image: `${wiredBase}/Chairman-Unit-SV-DWC-M230D.webp`,
        description: 'Full digital wired delegate discussion unit for the SV-DWC conference system.',
        features: [
          'Patented appearance design with a high-end, solemn aesthetic aligned with modern design standards.',
          'Professional high-fidelity condenser microphone core with sensitive sound pickup and clear voice; frequency bandwidth reaches 20 Hzâ€“20 kHz.',
          'Anti-interference circuit design helps prevent interference from mobile phones and other electronic products.',
          'The microphone head has a speaking light ring that displays the speaking and closing status of the unit.',
          'The speaking switch button has a translucent speaking pattern that remains illuminated while speaking.',
          'Passive unit powered by the system host; the 24 V input voltage is within the safe range.',
          'Connected by a 1.5 m Ã— 2 m T-type 8-core wire and Category 6 network cable; shielding reduces strong electromagnetic interference.',
          'The microphone unit has a built-in speaker and independent electronic volume adjustment.',
          'Built-in 1.77-inch screen displays the clock, ID code, speaker volume, microphone switch icon and other information.',
        ],
        specifications: [
          ['Working voltage', 'DC 24 V (supplied by the host)'],
          ['Input and output', '8P-DIN T-cable; Category 6 network cable'],
          ['Input', 'Cardioid electret'],
          ['Sensitivity', 'âˆ’46 dBV/Pa'],
          ['Frequency response', '20 Hzâ€“20 kHz'],
          ['Input impedance', '2 kÎ©'],
          ['Directivity', '0Â°/180Â° > 20 dB (1 kHz)'],
          ['Equivalent noise', '20 dBA (SPL)'],
          ['Maximum microphone sound pressure level', '125 dB (THD <3%)'],
          ['Signal-to-noise ratio', '>80 dB'],
          ['Channel crosstalk', '>80 dB'],
          ['Total harmonic distortion', '<0.05%'],
          ['Display', '128 Ã— 32 PMOLED'],
          ['External dimensions (excluding microphone stem)', '188 Ã— 128 Ã— 52 mm'],
          ['Weight', '1.0 kg'],
          ['Color', 'Gray and black'],
          ['Installation', 'Desktop'],
        ],
      },
      makeM805('C', 'Chairman'),
      makeM805('D', 'Delegate'),
      make6200('C', 'Chairman'),
      make6200('D', 'Delegate'),
      {
        slug: 'svh-dwc-cs500c',
        role: 'Chairman Unit',
        name: 'Digital Desktop Chairman Microphone',
        model: 'SVH-DWC-CS500C',
        image: wiredBase + '/SVH-DWC-CS500C.webp',
        description: 'Digital desktop chairman microphone with an adjustable gooseneck, accessible talk control and optional integrated speaker.',
        features: [
          'Gooseneck design with adjustable height and angle.',
          'Suitable as a digital desktop chairman microphone for conference systems.',
          'Talk button with graphic and Braille dual symbols.',
          'Expandable dual backup for audio redundancy.',
          'Built-in AGC for stable audio pickup.',
          'Effective pickup distance: 50–60 cm.',
          'Optional Class D speaker; automatically mutes when the microphone is active.',
          'Ring Daisy-Chain connection via 8-PIN or CAT5.',
          'Compatible with intelligent digital conference system deployment.',
          'Auto camera tracking and screen switching support.',
        ],
        specifications: [
          ['Product type', 'Digital desktop chairman microphone'],
          ['Original model', 'HY-CS500C'],
          ['Synoveta model', 'SVH-DWC-CS500C'],
          ['Series', 'Intelligent Digital Conference'],
          ['Installation type', 'Desktop'],
          ['Microphone design', 'Gooseneck'],
          ['Adjustment', 'Adjustable height / angle'],
          ['Talk button', 'Graphic and Braille dual symbols'],
          ['Audio redundancy', 'Expandable dual backup'],
          ['AGC', 'Built-in'],
          ['Effective pickup distance', '50–60 cm'],
          ['Optional speaker', 'Class D speaker, auto-mute when microphone is active'],
          ['Connection type', 'Ring Daisy-Chain (8-PIN or CAT5)'],
          ['Camera function', 'Auto camera tracking & screen switching'],
        ],
      },      {
        slug: 'svh-dwc-6500msr',
        role: 'Conference Host',
        name: 'Multi-Function Conference Host',
        model: 'SVH-DWC-6500MSR',
        image: wiredBase + '/SVH-DWC-6500MSR.webp',
        description: 'Multi-function host and controller for the Intelligent Digital Conference System, with integrated DSP, flexible conference modes and support for up to 180 units.',
        features: [
          'Built-in DSP with adaptive feedback suppression.',
          '6 conference unit outputs; supports up to 180 units.',
          'Supports 8-pin DIN/CAT5 daisy-chain, junction box and T-adapter connections.',
          'FIFO conference mode with speaker limit adjustable from 1 to 6.',
          'Open Discussion mode supports unlimited simultaneous speakers.',
          'Camera tracking supports VISCA and PELCO-D/P protocols.',
          'USB recording and playback for meeting audio.',
          'Designed as the host/controller for the Intelligent Digital Conference System.',
        ],
        specifications: [
          ['Product type', 'Multi-Function Conference Host'],
          ['Original model', 'HY-6500MSR'],
          ['Synoveta model', 'SVH-DWC-6500MSR'],
          ['System', 'Intelligent Digital Conference System'],
          ['Audio processing', 'Built-in DSP with adaptive feedback suppression'],
          ['Unit outputs', '6'],
          ['System capacity', 'Up to 180 conference units'],
          ['Supported connections', '8-pin DIN/CAT5 daisy-chain, junction box, T-adapter'],
          ['FIFO speaker limit', '1–6 simultaneous speakers'],
          ['Open Discussion mode', 'Unlimited simultaneous speakers'],
          ['Camera tracking protocols', 'VISCA, PELCO-D/P'],
          ['Recording / playback', 'USB meeting audio recording and playback'],
        ],
      },
    ],
  },
  'wifi-wireless-conference': {
    slug: 'wifi-wireless-conference',
    eyebrow: 'Wireless conference solution',
    name: 'Wi-Fi Wireless Conference System',
    shortName: 'Wi-Fi Wireless Conference',
    modelFamily: 'SV-WWC Series',
    description: 'A flexible wireless conference system for modern meeting rooms that need an uncluttered table layout and adaptable deployment.',
    heroImage: `${wirelessBase}/wifi-wireless-conference-system-banner-image.webp`,
    overview: 'The SV-WWC series combines a central system controller with two styles of chairman and delegate discussion units. The coordinated range gives meeting-room designers a consistent wireless system with a choice of tabletop formats.',
    highlights: ['Central wireless system controller', 'Chairman and delegate unit options', 'Two coordinated tabletop unit designs'],
    products: [
      {
        slug: 'sv-dwc-c800s',
        role: 'System Controller',
        name: 'Digital Conference System Controller',
        model: 'SV-DWC-C800S',
        image: `${wirelessBase}/Conference-System-Controller-SV-DWC-C800S.webp`,
        description: 'High-capacity digital conference system controller supporting both wired and wireless conference units.',
        features: [
          'Standard 2U chassis design. One CAT6 network cable transmits 64 channels of audio and information, supporting both wired and wireless conferences.',
          'Adaptive interference-avoidance technology provides strong anti-interference capability. Based on IEEE 802.11n Wi-Fi 6, it supports 2.4 GHz and 5 GHz wireless signals.',
          'Supports up to 5,300 wired conference units and 300 wireless conference units, with up to 14 microphones speaking simultaneously: 8 wired and 6 wireless.',
          'Built-in high-performance DSP processor supports 10-band EQ, delay, volume and other host-output adjustments; optional howling suppression is supported.',
          'Four microphone management modes are supported: FIFO (first in, first out), NORMAL, VOICE (voice control) and APPLY (application mode).',
          'Audio interfaces include one RCA and one XLR input plus one RCA and one XLR output. Output channels support EQ, delay and volume adjustment, with optical-fiber and coaxial audio outputs.',
          'Supports USB flash-drive recording with advanced noise elimination, one-button recording from the front panel, recording-status indication and host headphone monitoring.',
          'Supports docking with voice-transcription equipment to achieve role separation.',
        ],
        specifications: [
          ['Microphone capacity', 'Wired microphones â‰¤5,300; wireless microphones â‰¤300'],
          ['Simultaneous interpretation channels', '63 + 1 channels'],
          ['Frequency response', '80 Hzâ€“16 kHz'],
          ['Signal-to-noise ratio', '>80 dB(A)'],
          ['Dynamic range', '>80 dB'],
          ['Total harmonic distortion', '<0.05%'],
          ['Main power supply', 'Wide-range power supply: 100â€“240 VAC'],
          ['EXTENSION port', 'Connects conference-system expansion equipment'],
          ['AP network port', 'Connects a wireless access point'],
          ['PC network port', 'Connects a computer'],
          ['Static power consumption', '30 W'],
          ['Output power consumption', '150 W'],
          ['Wired microphone connection method', 'Dedicated cable'],
          ['Touch-screen control', '4.3-inch full-color touch screen'],
          ['UNIT', '4 Ã— 6-core aviation interfaces'],
        ],
      },
      {
        slug: 'sv-wwc-m809c',
        role: 'Chairman Unit',
        name: '5G Wi-Fi Wireless Chairman Unit',
        model: 'SV-WWC-M809C',
        image: `${wirelessBase}/Wireless-Chairman-Unit-SV-WWC-M809C.webp`,
        description: '5G Wi-Fi wireless chairman discussion unit with a full-color display and rechargeable battery.',
        features: [
          ...m809CommonFeatures.slice(0, 9),
          'The chairman-priority function can turn off the microphones of all representatives who are speaking.',
          ...m809CommonFeatures.slice(9),
        ],
        specifications: m809Specifications,
      },
      {
        slug: 'sv-wwc-m809d',
        role: 'Delegate Unit',
        name: '5G Wi-Fi Wireless Delegate Unit',
        model: 'SV-WWC-M809D',
        image: `${wirelessBase}/Wireless-Chairman-Unit-SV-WWC-M809D.webp`,
        description: '5G Wi-Fi wireless delegate discussion unit with a full-color display and rechargeable battery.',
        features: m809CommonFeatures,
        specifications: m809Specifications,
      },
      {
        slug: 'sv-wwc-m810c',
        role: 'Chairman Unit',
        name: '5G Wi-Fi Premium Chairman Unit',
        model: 'SV-WWC-M810C',
        image: `${wirelessBase}/Wireless-Chairman-Unit-SV-WWC-M810C.webp`,
        description: 'Premium 5G Wi-Fi wireless chairman discussion unit with a 5.0-inch IPS display and rechargeable battery.',
        features: [
          ...m810CommonFeatures.slice(0, 7),
          'The chairman-priority function can turn off the microphones of representatives who are speaking.',
          ...m810CommonFeatures.slice(7),
        ],
        specifications: m810Specifications,
      },
      {
        slug: 'sv-wwc-m810d',
        role: 'Delegate Unit',
        name: '5G Wi-Fi Premium Delegate Unit',
        model: 'SV-WWC-M810D',
        image: `${wirelessBase}/Wireless-Chairman-Unit-SV-WWC-M810D.webp`,
        description: 'Premium 5G Wi-Fi wireless delegate discussion unit with a 5.0-inch IPS display and rechargeable battery.',
        features: m810CommonFeatures,
        specifications: m810Specifications,
      },
    ],
  },
};

// Show the newly approved catalogue first in each system, followed by the
// legacy range. Matching legacy records are merged instead of duplicated.
for (const [systemType, system] of Object.entries(conferenceSystems)) {
  const approvedProducts = approvedConferenceProducts.filter(
    (product) => product.systemType === systemType
  );
  const approvedModels = new Set(approvedProducts.map((product) => product.model));
  const legacyProductsByModel = new Map(
    system.products.map((product) => [product.model, product])
  );

  system.products = [
    ...approvedProducts.map((product) => ({
      ...legacyProductsByModel.get(product.model),
      ...product,
    })),
    ...system.products.filter((product) => !approvedModels.has(product.model)),
  ];
}

export const conferenceSystemSlugs = Object.keys(conferenceSystems);




